### ISSUE TITLE
急急急，打不出汉字

### ISSUE THREAD

**Issue by yyyyyu2799** [X-lab2017/dase-2023-autumn#14]
电脑突然打不出汉字了怎么办，不管是中文输入法还是英文输入法都只有字母，尝试了网上的好几种方法也没有用

**Comment by yyyyyu2799** [comment]
![image](https://github.com/X-lab2017/dase-2023-autumn/assets/144769353/f00d27c4-c076-4162-ae40-843f70209952)

**Comment by andyhuang18** [comment]
@yyyyyu2799 这个问题和课程没有关联，可以通过别的渠道了解解决方法

**Comment by PureNatural** [comment]
尝试重启电脑

**Comment by wj23027** [comment]
issue 中尽量提与课程有关的问题~
